import { createHmac, timingSafeEqual } from 'crypto';
import { Injectable, NestMiddleware } from '@nestjs/common';

/**
 * Middleware that verifies HMAC-SHA256 signatures generated by
 * `LocalDisk.temporaryUrl()` when `DiskConfig.signSecret` is set.
 *
 * Mount this middleware on the route(s) that serve local files.
 * It reads `?expires=<unix_ts>&signature=<hex>` from the query string
 * and returns 403 if the signature is invalid or the URL has expired.
 *
 * @example
 * ```ts
 * // app.module.ts
 * export class AppModule implements NestModule {
 *   configure(consumer: MiddlewareConsumer) {
 *     consumer
 *       .apply(LocalSignedUrlMiddleware)
 *       .forRoutes({ path: '/files/*', method: RequestMethod.GET });
 *   }
 * }
 * ```
 */
@Injectable()
export class LocalSignedUrlMiddleware implements NestMiddleware {
  constructor(private readonly signSecret: string) {}

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  use(req: any, res: any, next: () => void): void {
    const { expires, signature } = req.query as Record<string, string | undefined>;

    if (!expires || !signature) {
      res.status(403).json({ message: 'Missing signature parameters' });
      return;
    }

    const expiresAt = parseInt(expires, 10);
    if (isNaN(expiresAt) || Math.floor(Date.now() / 1000) > expiresAt) {
      res.status(403).json({ message: 'URL has expired' });
      return;
    }

    // Reconstruct the same path used when the URL was signed (strip leading slash)
    const rawPath: string = req.path ?? req.url?.split('?')[0] ?? '';
    const normalizedPath = rawPath.startsWith('/') ? rawPath.slice(1) : rawPath;

    const payload = `${normalizedPath}:${expiresAt}`;
    const expected = createHmac('sha256', this.signSecret).update(payload).digest('hex');

    try {
      const expectedBuf = Buffer.from(expected, 'hex');
      const providedBuf = Buffer.from(signature, 'hex');

      if (
        expectedBuf.length !== providedBuf.length ||
        !timingSafeEqual(expectedBuf, providedBuf)
      ) {
        res.status(403).json({ message: 'Invalid signature' });
        return;
      }
    } catch {
      res.status(403).json({ message: 'Invalid signature' });
      return;
    }

    next();
  }
}
